encuestas/encuestas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('clientes/', include('menuUno.urls')),
    path('admin/', admin.site.urls),
    path('', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

encuestas/menuUno/urls.py
from django.urls import path, include

from . import views

app_name = 'menuUno'
urlpatterns = [
    # path('', views.nota_lista, name='nota_list'),
    path('listaClientes', views.persona_lista, name='persona_list'),
    path('listaNotas', views.nota_lista, name='nota_list'),
    path('<int:persona_pk>/<int:nota_pk>', views.nota_detail, name='nota_detail'),
    path('<int:pk>/', views.persona_detail, name='persona_detail'),
    path('<int:pk>/', views.nota_detail, name='nota_detail'),
    path('createPersona/', views.persona_create_view, name='persona_create'),
    path('createNota/<int:pk>', views.nota_create_view, name='nota_create'),
    path('createItem/<int:persona_pk>/<int:nota_pk>', views.item_create_view, name='item_create'),

]

encuestas/menuUno/models.py
from django.db import models

# Create your models here.
# class Nota(models.Model):
#     auto_id_nota = models.AutoField(primary_key=True)  
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.auto_id_nota

class Persona(models.Model):
    auto_id_cliente = models.AutoField(primary_key=True)  
    created_at = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    celular = models.CharField(max_length=255)
    telefono = models.CharField(max_length=255)
    email = models.EmailField(blank=True)
    info = models.CharField(max_length=255)

    class Meta:
        ordering = ['auto_id_cliente', ]

    def __str__(self):
        return 'No.:' + str(self.auto_id_cliente) + ' - ' + self.nombre + ' ' + self.apellido + ' ' + self.info

class Nota(models.Model):
    auto_id_nota = models.AutoField(primary_key=True)  
    created_at = models.DateTimeField(auto_now_add=True)
    tipo = models.CharField(max_length=255)
    receptor = models.CharField(max_length=255)
    person = models.ForeignKey(Persona, on_delete=models.CASCADE)

    def __str__(self):
        return 'No.:' + str(self.auto_id_nota) + ' ' + self.person.nombre + ' ' + self.person.apellido

class Item(models.Model):
    auto_id_item = models.AutoField(primary_key=True)     
    descripción = models.CharField(max_length=255)
    serie = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    cargador = models.CharField(max_length=255)
    funda = models.CharField(max_length=255)
    cables = models.CharField(max_length=255)
    cartuchos = models.CharField(max_length=255)
    falla = models.CharField(max_length=255)
    nota = models.ForeignKey(Nota, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.auto_id_item)


# Create your models here.
# class Notas(models.Model):
#     created_at = models.DateTimeField(auto_now_add=True)
#     auto_id_nota = models.AutoField(primary_key=True)  

#     def __str__(self):
#         return self.nombre

encuestas/menuUno/forms.py
from django import forms


from .models import Persona, Nota, Item
# from .models import Nota

NOTA_CHOICES = [
    ('servicio_cliente', 'Cliente particular'),
    ('servicio_empresa', 'Empresa'),
    ('venta', 'Venta'),
    ('garantia', 'Garantía'),
    ]

class RawPersonaForm(forms.Form):
    nombre = forms.CharField(required=True)
    apellido = forms.CharField(required=True)
    celular = forms.CharField(required=True)
    telefono = forms.CharField(required=False)
    email = forms.CharField(required=False)
    info = forms.CharField(required=False)

# class RawNotaForm(forms.Form):
#     tipo = forms.CharField(label='¿Qué tipo de nota es?', widget=forms.Select(choices=NOTA_CHOICES))
#     receptor = forms.CharField(required=True)


class NotaForm(forms.ModelForm):
    class Meta:
        model = Nota
        fields = (
            'tipo',
            'person',
            'receptor'
        )
        widgets = {
            'tipo': forms.Select(choices=NOTA_CHOICES),
        }

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = (
            'nota',
            'descripción',
            'serie',
            'password',
            'cargador',
            'funda',
            'cables',
            'cartuchos',
            'falla',
        )

class RawNotaForm(forms.Form):
    tipo = forms.CharField(required=True)
    person = forms.CharField(required=True)
    receptor = forms.Select(choices=NOTA_CHOICES)

# class RawItemForm(forms.Form):
#     descripción = forms.CharField(required=True)
#     serie = forms.CharField(required=True)
#     password = forms.CharField(required=False)
#     cargador = forms.CharField(required=False)
#     funda = forms.CharField(required=False)
#     cables = forms.CharField(required=False)
#     cartuchos = forms.CharField(required=False)
#     falla = forms.CharField(required=True)
 

# class PersonaForm(forms.ModelForm):
#     class Meta:
#         model = Persona
#         fields = [
#             'name',
#             'lastName',
#             'ocupacion',
#             'redSocialUno',
#         ]

# class NaotForm(forms.ModelForm):
#     class Meta:
#         model = Encuesta
#         fields = [
#             'title',
#             'description',
#         ]

# class RawEncuestaForm(forms.Form):
#     title = forms.CharField(required=True)
#     description = forms.CharField(
#                         required=True,
#                         widget=forms.Textarea(
#                             attrs={
#                                 "rows" : 10,
#                                 "cols" : 70,
#                             }
#                         )
#                     )

encuestas/encuestas/views.py
from django.shortcuts import render

def hello_world(request):
    return render(request, 'home.html')

encuestas/menuUno/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import ListView

from .forms import RawPersonaForm, NotaForm, ItemForm, RawNotaForm
from.models import Persona, Nota, Item

# def encuesta_create_view(request):
#     my_form = RawEncuestaForm()
#     if request.method == "POST":
#         my_form = RawEncuestaForm(request.POST)
#         if my_form.is_valid():
#             print(my_form.cleaned_data)
#             Encuesta.objects.create(**my_form.cleaned_data)
#             return redirect('/encuestas')
#         else:
#             print(my_form.errors)
#     context= {
#         "form": my_form
#     }
#     return render(request, 'encuestas/encuesta_create.html', context)


def persona_create_view(request):
    my_form = RawPersonaForm()
    if request.method == "POST":
        my_form = RawPersonaForm(request.POST)
        if my_form.is_valid():
            #print(my_form.cleaned_data)
            Persona.objects.create(**my_form.cleaned_data)
            personaId = Persona.objects.latest('auto_id_cliente') 
            #print(personaId.auto_id_cliente)
            #persona = my_form.cleaned_data['person']
            return redirect('menuUno:nota_create', personaId.auto_id_cliente)
        else:
            print(my_form.errors)
    notas = Nota.objects.all()
    personas = Persona.objects.all()
    context = {
        "form": my_form , 'personas': personas, 'notas': notas
    }
    return render(request, 'encuestas/persona_create.html', context)


def nota_create_view(request, pk):
    my_form = NotaForm()
    notas = Nota.objects.all()
    item = Item.objects.all()
    personas = Persona.objects.all()
    personaPk = get_object_or_404(Persona, pk=pk)
    if request.method == "POST":
        my_form = NotaForm(request.POST)
        if my_form.is_valid():
            #print(my_form.cleaned_data)
            persona = my_form.cleaned_data['person']
            #print(persona)
            pk = persona.auto_id_cliente
            #print(persona.auto_id_cliente)
            Nota.objects.create(**my_form.cleaned_data)
            personaDato = get_object_or_404(Persona, pk=pk)
            notaId = Nota.objects.latest('auto_id_nota') 
            #print(notaId.auto_id_nota)
            return redirect('menuUno:item_create', persona.auto_id_cliente, notaId.auto_id_nota)
        else:
            print(my_form.errors)
    context = {
        "form": my_form , 'personas': personas, 'notas': notas, 'persona': personaPk,
    }
    return render(request, 'encuestas/nota_create.html', context)


def item_create_view(request, persona_pk, nota_pk):
    my_form = ItemForm()
    nota = get_object_or_404(Nota, person_id = persona_pk, pk = nota_pk)
    persona = get_object_or_404(Persona, pk=persona_pk)
    items = Item.objects.all()
    if request.method == "POST":
        my_form = ItemForm(request.POST)
        if my_form.is_valid():
            #print(my_form.cleaned_data)
            Item.objects.create(**my_form.cleaned_data)
            return redirect('menuUno:item_create', persona.auto_id_cliente, nota.auto_id_nota)
        else:
            print(my_form.errors)
    notas = Nota.objects.all()
    #personas = Persona.objects.all()
    persona = get_object_or_404(Persona, pk=persona_pk)
    context = {
        "form": my_form , 'persona': persona, 'notas': notas, 'items': items, 'nota': nota,
    }
    return render(request, 'encuestas/item_create.html', context)


# class NotaCreateView(CreateView):

#     model = Nota
#     form_class = NotaForm
#     template_name = "encuestas/nota_create.html"
#     success_url = reverse_lazy("menuUno:item_create")

# class ItemCreateView(CreateView):

#     model = Item
#     form_class = ItemForm
#     template_name = "encuestas/item_create.html"
#     success_url = reverse_lazy("menuUno:item_create")


# def persona_create_view(request):
#     form = PersonaForm(request.POST or None)
#     if form.is_valid():
#         form.save()

#     context= {
#         'form': form,
#     }
#     return render(request, 'encuestas/persona_create.html', context)

# def encuesta_create_view(request):
#     form = EncuestaForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         form = EncuestaForm()

#     context= {
#         'form': form,
#     }
#     return render(request, 'encuestas/encuesta_create.html', context)

# def encusta_lista(request):
#     encuestas = Encuesta.objects.all()
#     return render(request, 'encuestas/encuesta_list.html', {'encuestas': encuestas})


# def encuesta_detail(request, pk):
#     # encuesta = Encuesta.objects.get(pk=pk)
#     encuesta = get_object_or_404(Encuesta, pk=pk)
#     return render(request, 'encuestas/detalle_encuesta.html', {'encuesta': encuesta})

def persona_detail(request, pk):
    notas = Nota.objects.all()
    persona = get_object_or_404(Persona, pk=pk)
    item = Item.objects.all()
    return render(request, 'encuestas/persona_detail.html',{'persona': persona, 'notas' : notas, 'item' : item})

def persona_lista(request):
    notas = Nota.objects.all()
    personas = Persona.objects.all()
    return render(request, 'encuestas/persona_list.html', {'personas': personas, 'notas' : notas})

def nota_detail(request, persona_pk, nota_pk,):
    nota = get_object_or_404(Nota, person_id = persona_pk, pk = nota_pk)
    persona = get_object_or_404(Persona, pk=persona_pk)
    items = Item.objects.all()
    return render(request, 'encuestas/nota_detail.html', {'persona': persona, 'nota': nota, 'items': items})

def nota_lista(request):
    notas = Nota.objects.all()
    return render(request, 'encuestas/nota_list.html', {'notas': notas})

encuestas/menuUno/templates/encuestas/detalle_encuesta.html
{% extends "layout.html" %}

{% block title %} {{encuesta.title}} {% endblock %}

{% block content %}

<article>
    <h2>{{ encuesta.title }}</h2>
    {{ encuesta.description}}
    <p>Esta encuesta tiene el siguiente número de encuestados {{ encuesta.persona_set.count }} y son : {{ encuesta.persona_set.all|join:", " }}</p>
    <section>
        {% for persona in encuesta.persona_set.all %}
            <h3>
                <!-- <a href="{% url 'menuUno:persona_detail' encuesta_pk=persona.encuesta.pk persona_pk=persona.pk %}">{{persona.name}}</a> -->
            </h3>
            {{ persona.redSocialUno }}
        {% endfor %}
    </section>    
</article>
    

{% endblock %}

encuestas/menuUno/templates/encuestas/encuesta_create.html
{% extends "layout.html" %}

{% block title %}Notas - Reset Systems{% endblock %}}

{% block content %}
<form action='.' method="POST"> {% csrf_token %}
        {{ form.as_p }}
<input  type='submit' value='Save' />  
</form>
{% endblock %}

encuestas/menuUno/templates/encuestas/encuesta_list.html
{% extends "layout.html" %}

{% block title %}Notas - Reset Systems{% endblock %}}

{% block content %}
    <div class="cards">
        {% for encuesta in encuestas %}
            <div class="card">
                <!-- <header><a href="{% url 'menuUno:encuesta_detail' pk=encuesta.pk %}">{{encuesta.title}}</a></header> -->
                <div class="card-copy">
                    {{encuesta.description}}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

encuestas/menuUno/templates/encuestas/item_create.html
{% extends "layout.html" %}

{% block title %}Items-Reset Systems{% endblock %}}

{% block content %}
        <div class="cards">
                <div class="card">
                    <header>Agregar Item</header>
                    <div class="card-copy">
                        <form method="POST"> {% csrf_token %}
                        {{form.as_p}}
                        <input  type='submit' value='Save' />  
                        </form>
                    </div>  
                </div>  
            </div>  
        <div class="cards">
                <div class="card">
                    <header> Nombre: {{ persona.nombre }}  {{ persona.apellido }} </header>
                    <div class="card-copy">
                        <p>Teléfono celular:{{persona.celular}}</p>
                        <p>Teléfono: {{persona.telefono}}</p>
                        <p>Email: {{persona.email}}</p>
                        <p>Información: {{persona.info}}</p>
                    </div>      
                </div>
            </div>
            <div class="cards">
                    <div class="card">
                            <header>
                                <a>Nota: {{nota.auto_id_nota}}</a>
                            </header>
                        <div class="card-copy">
                            {% load static %} <img src="{% static "images/logoreset.png" %}" alt="Reset Systems" height="31" width="82" />
        
                            <h3>Reset Systems.  &nbsp;&nbsp;&nbsp;&nbsp;  Teléfono: 574 97 97.  &nbsp;&nbsp;&nbsp;&nbsp;  Dirección: 8 Sur 3102. Puebla, México &nbsp;&nbsp;&nbsp;&nbsp; resetcompany.net</h3>
                            <p>Nombre: {{ persona.nombre }} {{ persona.apellido }}</p>
                            <p>Fecha y hora de ingreso: {{nota.created_at|date:"M d, Y. h:m:s"}}</p>
                            <p>Nota:{{nota.tipo}}</p>
                        </div>
                    {% for item in nota.item_set.all %}
                    <div class="card">
                        <header>
                            <a>Item</a>
                        </header>
                        <table>
                            <tr>
                                <th>Descripción</th>
                                <th>Número de serie</th>
                                <th>Password</th>
                                <th>Cargador</th>
                                <th>Funda</th>
                                <th>Cables</th>
                                <th>Cartuchos</th>
                                <th>Falla</th>
                            </tr>
                            <tr> 
                                <td>{{ item.descripción }}</td>
                                <td>{{ item.serie }}</td>
                                <td>{{ item.password }}</td>
                                <td>{{ item.cargador }}</td>
                                <td>{{ item.funda }}</td>
                                <td>{{ item.cables }}</td>
                                <td>{{ item.cartuchos }}</td>
                                <td>{{ item.falla }}</td>
                            </tr>
                        </table>
                    </div>
                    {% endfor %}
                </div>            
        </div>
{% endblock %}

encuestas/menuUno/templates/encuestas/nota_create.html
{% extends "layout.html" %}

{% block title %}Notas - Reset Systems{% endblock %}}

{% block content %}
        <div class="cards">
            <div class="card">
                <header>Crear Nota</header>
                <div class="card-copy">
                    <form method="POST"> {% csrf_token %}
                    {{form.as_p}}
                    <input  type='submit' value='Save' />  
                    </form>
                </div>  
            </div>  
        </div>  
        <div class="cards">
            <div class="card">
                <header> Nombre: {{ persona.nombre }} {{ persona.apellido }} </header>
                <div class="card-copy">
                    <p>Teléfono celular:{{persona.celular}}</p>
                    <p>Teléfono: {{persona.telefono}}</p>
                    <p>Email: {{persona.email}}</p>
                    <p>Información: {{persona.info}}</p>
                </div>      
            </div>
        </div>
        <h3>Listado de clientes</h3>
        <div class="cards">
            {% for persona in personas %}
                <div class="card">
                   <header><a href="{% url 'menuUno:persona_detail' pk=persona.pk %}">Número Cliente:{{persona.auto_id_cliente}} {{persona.nombre}} {{persona.apellido}}</a></header>
                    <div class="card-copy">
                        Número de notas: {{persona.nota_set.count}}
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

encuestas/menuUno/templates/encuestas/nota_detail.html
{% extends "layout.html" %}

{% block title %} Detalle Nota {% endblock %}

{% block content %}
    <div class="cards">
                <div class="card">
                        <header>
                            <a>Nota: {{nota.auto_id_nota}}</a>
                        </header>
                    <div class="card-copy">
                        {% load static %} <img src="{% static "images/logoreset.png" %}" alt="Reset Systems" height="31" width="82" />
    
                        <h3>Reset Systems.  &nbsp;&nbsp;&nbsp;&nbsp;  Teléfono: 574 97 97.  &nbsp;&nbsp;&nbsp;&nbsp;  Dirección: 8 Sur 3102. Puebla, México &nbsp;&nbsp;&nbsp;&nbsp; resetcompany.net</h3>
                        <p>Nombre: {{ persona.nombre }} {{ persona.apellido }}</p>
                        <p>Fecha y hora de ingreso: {{nota.created_at|date:"M d, Y. h:m:s"}}</p>
                        <p>Nota:{{nota.tipo}}</p>
                    </div>
                {% for item in nota.item_set.all %}
                <div class="card">
                    <header>
                        <a>Item</a>
                    </header>
                    <table>
                        <tr>
                            <th>Descripción</th>
                            <th>Número de serie</th>
                            <th>Password</th>
                            <th>Cargador</th>
                            <th>Funda</th>
                            <th>Cables</th>
                            <th>Cartuchos</th>
                            <th>Falla</th>
                        </tr>
                        <tr> 
                            <td>{{ item.descripción }}</td>
                            <td>{{ item.serie }}</td>
                            <td>{{ item.password }}</td>
                            <td>{{ item.cargador }}</td>
                            <td>{{ item.funda }}</td>
                            <td>{{ item.cables }}</td>
                            <td>{{ item.cartuchos }}</td>
                            <td>{{ item.falla }}</td>
                        </tr>
                    </table>
                </div>
                {% endfor %}
            </div>            
    </div>
{% endblock %}

encuestas/menuUno/templates/encuestas/nota_list.html
{% extends "layout.html" %}

{% block title %}Notas - Reset Systems {% endblock %}}

{% block content %}
    <div class="cards">
        {% for nota in notas %}
            <div class="card">
                <!-- <header><a href="{% url 'menuUno:nota_detail' pk=nota.pk %}">Nota:{{persona.auto_id_cliente}} {{persona.nombre}} {{persona.apellido}}</a></header> -->
               <header>Nota:{{nota.auto_id_nota}} - {{nota.tipo}}</header>
                <div class="card-copy">
                    Nombre del cliente:{{persona.nombre|linebreaks }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

encuestas/menuUno/templates/encuestas/persona_create.html
{% extends "layout.html" %}

{% block title %}Notas - Reset Systems{% endblock %}}

{% block content %}
    <div class="cards">
        <div class="card">
            <header>Registrar cliente nuevo</header>
            <div class="card-copy">
                <form method="POST"> {% csrf_token %}
                {{form.as_p}}
                <input  type='submit' value='Save' />  
                </form>
            </div>  
        </div>  
    </div>  
        <h3>Listado de clientes</h3>
        <div class="cards">
            {% for persona in personas %}
                <div class="card">
                   <header><a href="{% url 'menuUno:persona_detail' pk=persona.pk %}">Número Cliente:{{persona.auto_id_cliente}} {{persona.nombre}} {{persona.apellido}}</a></header>
                    <div class="card-copy">
                        Número de notas: {{persona.nota_set.count}}
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

encuestas/menuUno/templates/encuestas/persona_detail.html
{% extends "layout.html" %}

{% block title %} Detalles cliente {% endblock %}

{% block content %}
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>

<div class="cards">
    <div class="card">
        <header> Nombre: {{ persona.nombre }} {{ persona.apellido }} </header>
        <div class="card-copy">
            <p>Teléfono celular:{{persona.celular}}</p>
            <p>Teléfono: {{persona.telefono}}</p>
            <p>Email: {{persona.email}}</p>
            <p>Información: {{persona.info}}</p>
        </div>      
    </div>
</div>

<div class="cards">
        {% for nota in persona.nota_set.all %}
            <div class="card">
                    <header>
                        <a href="{% url 'menuUno:nota_detail' persona_pk=nota.person.pk nota_pk=nota.pk%}">Nota: {{nota.auto_id_nota}}</a>
                    </header>
                <div class="card-copy">
                    {% load static %} <img src="{% static "images/logoreset.png" %}" alt="Reset Systems" height="31" width="82" />

                    <h3>Reset Systems.  &nbsp;&nbsp;&nbsp;&nbsp;  Teléfono: 574 97 97.  &nbsp;&nbsp;&nbsp;&nbsp;  Dirección: 8 Sur 3102. Puebla, México &nbsp;&nbsp;&nbsp;&nbsp; resetcompany.net</h3>
                    <p>Nombre: {{ persona.nombre }} {{ persona.apellido }}</p>
                    <p>Fecha y hora de ingreso: {{nota.created_at|date:"M d, Y. h:m:s"}}</p>
                    <p>Nota:{{nota.tipo}}</p>
                </div>
            {% for item in nota.item_set.all %}
            <div class="card">
                <header>
                    <a>Item</a>
                </header>
                <table>
                    <tr>
                        <th>Descripción</th>
                        <th>Número de serie</th>
                        <th>Password</th>
                        <th>Cargador</th>
                        <th>Funda</th>
                        <th>Cables</th>
                        <th>Cartuchos</th>
                        <th>Falla</th>
                    </tr>
                    <tr> 
                        <td>{{ item.descripción }}</td>
                        <td>{{ item.serie }}</td>
                        <td>{{ item.password }}</td>
                        <td>{{ item.cargador }}</td>
                        <td>{{ item.funda }}</td>
                        <td>{{ item.cables }}</td>
                        <td>{{ item.cartuchos }}</td>
                        <td>{{ item.falla }}</td>
                    </tr>
                </table>
            </div>
            {% endfor %}
            </div>
        {% endfor %}
        
</div>
{% endblock %}

encuestas/menuUno/templates/encuestas/persona_list.html
{% extends "layout.html" %}

{% block title %} Clientes - Reset Systems {% endblock %}}

{% block content %}
    <div class="cards">
        {% for persona in personas %}
            <div class="card">
               <header><a href="{% url 'menuUno:persona_detail' pk=persona.pk %}">Número Cliente:{{persona.auto_id_cliente}} {{persona.nombre}} {{persona.apellido}}</a></header>
                <div class="card-copy">
                    Número de notas: {{persona.nota_set.count}}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}