encuestas/encuestas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('clientes/', include('menuUno.urls')),
    path('admin/', admin.site.urls),
    path('', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

encuestas/menuUno/urls.py
from django.urls import path, include

from . import views

app_name = 'menuUno'
urlpatterns = [
    # path('', views.nota_lista, name='nota_list'),
    path('listaClientes', views.persona_lista, name='persona_list'),
    path('listaNotas', views.nota_lista, name='nota_list'),
    path('<int:persona_pk>/<int:nota_pk>', views.nota_detail, name='nota_detail'),
    path('<int:pk>/', views.persona_detail, name='persona_detail'),
    path('<int:pk>/', views.nota_detail, name='nota_detail'),
    path('createPersona/', views.persona_create_view, name='persona_create'),
    path('createNota/<int:pk>', views.nota_create_view, name='nota_create'),
    path('createItem/<int:persona_pk>/<int:nota_pk>', views.item_create_view, name='item_create'),

]

encuestas/encuestas/views.py
from django.shortcuts import render

def hello_world(request):
    return render(request, 'home.html')

encuestas/encuestas/templates/home.html
{% extends "layout.html" %}

{% block title %}Notas Reset Home TEST{% endblock %}}

{% block content %}

<div class="cards">
    <div class="card">
        {% load static %} <img src="{% static "images/logoreset.png" %}" alt="Reset Systems" height="62" width="162" />
        <header>BETA Como registrasr una nota:</header>
        <div class="card-copy">
            <p>1- Registrar al cliente (solo en caso de que sea nuevo) </p>
            <p>2- Crear nota,  seleccionar tipo de nota, al cliente  y capturar el nombre de quien recibe</p>  
            <p>3- Agregar Item, seleccionar número de nota y agregar descripción de cada item recibido </p>
            <p>4- Lista de clientes, seleccionar cliente, buscar la nota, dar click en el número </p>
            <p>5- Imprimir nota en pantalla como PDF para mandar por correo o whatsApp</p>
            {% endblock %}
        </div>  
    </div>  
</div>  

encuestas/encuestas/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet", href="{% static 'css/layout.css' %}">
</head>
<body>
    <div class="site-container">
        <nav>
            <a href="{% url 'home' %}">Home Notas Reset</a>
            <a href="{% url 'menuUno:persona_create' %}">Registrar cliente</a>
            <a href="{% url 'menuUno:nota_create' %}">Crear Nota</a>
            <a href="{% url 'menuUno:item_create' %}">Agregar item</a>
            <a href="{% url 'menuUno:persona_list' %}">Lista de clientes</a>
            <!-- <a href="{% url 'menuUno:nota_list' %}">Lista de Notas</a> -->
        </nav>
        {% block content %}{% endblock %}
    </div>
</body>
</html>